
version: '3.0'
services:
  web:
    # TODO: image, ports and redis dependency
    image: tomekzaw/io-lab-docker-ci-public
    ports:
      - 80:5000
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6.0-rc3
    # TODO: persistence for redis. You need to persist /data directory.
    volumes:
      - "redis-prod-data:/data"

volumes:
  redis-prod-data:
